//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18052
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// このソース コードは Microsoft.VSDesigner、バージョン 4.0.30319.18052 によって自動生成されました。
// 
#pragma warning disable 1591

namespace TRC_W_PWT_ProductView.KTAuthLogin {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ktauthLoginSOAP11Binding", Namespace="http://webmethod.svccom.tsukuba.kubota.co.jp")]
    public partial class ktauthLogin : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback authByActiveDirectoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback logoutOperationCompleted;
        
        private System.Threading.SendOrPostCallback authGiaMigByIDPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback authMigByIDPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback authByIDPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback changePasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback authGiaMigByIPAddressOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ktauthLogin() {
            this.Url = global::TRC_W_PWT_ProductView.Properties.Settings.Default.TRC_W_PWT_ProductView_KTAuthLogin_ktauthLogin;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event authByActiveDirectoryCompletedEventHandler authByActiveDirectoryCompleted;
        
        /// <remarks/>
        public event logoutCompletedEventHandler logoutCompleted;
        
        /// <remarks/>
        public event authGiaMigByIDPasswordCompletedEventHandler authGiaMigByIDPasswordCompleted;
        
        /// <remarks/>
        public event authMigByIDPasswordCompletedEventHandler authMigByIDPasswordCompleted;
        
        /// <remarks/>
        public event authByIDPasswordCompletedEventHandler authByIDPasswordCompleted;
        
        /// <remarks/>
        public event changePasswordCompletedEventHandler changePasswordCompleted;
        
        /// <remarks/>
        public event authGiaMigByIPAddressCompletedEventHandler authGiaMigByIPAddressCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:authByActiveDirectory", RequestNamespace="http://webmethod.svccom.tsukuba.kubota.co.jp", ResponseNamespace="http://webmethod.svccom.tsukuba.kubota.co.jp", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public WSUserInfoDto authByActiveDirectory([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string logonConfirmKey, bool useGuestUserOption, [System.Xml.Serialization.XmlIgnoreAttribute()] bool useGuestUserOptionSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string clientIPAddress) {
            object[] results = this.Invoke("authByActiveDirectory", new object[] {
                        logonConfirmKey,
                        useGuestUserOption,
                        useGuestUserOptionSpecified,
                        clientIPAddress});
            return ((WSUserInfoDto)(results[0]));
        }
        
        /// <remarks/>
        public void authByActiveDirectoryAsync(string logonConfirmKey, bool useGuestUserOption, bool useGuestUserOptionSpecified, string clientIPAddress) {
            this.authByActiveDirectoryAsync(logonConfirmKey, useGuestUserOption, useGuestUserOptionSpecified, clientIPAddress, null);
        }
        
        /// <remarks/>
        public void authByActiveDirectoryAsync(string logonConfirmKey, bool useGuestUserOption, bool useGuestUserOptionSpecified, string clientIPAddress, object userState) {
            if ((this.authByActiveDirectoryOperationCompleted == null)) {
                this.authByActiveDirectoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnauthByActiveDirectoryOperationCompleted);
            }
            this.InvokeAsync("authByActiveDirectory", new object[] {
                        logonConfirmKey,
                        useGuestUserOption,
                        useGuestUserOptionSpecified,
                        clientIPAddress}, this.authByActiveDirectoryOperationCompleted, userState);
        }
        
        private void OnauthByActiveDirectoryOperationCompleted(object arg) {
            if ((this.authByActiveDirectoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.authByActiveDirectoryCompleted(this, new authByActiveDirectoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:logout", RequestNamespace="http://webmethod.svccom.tsukuba.kubota.co.jp", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void logout([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string accessToken) {
            this.Invoke("logout", new object[] {
                        accessToken});
        }
        
        /// <remarks/>
        public void logoutAsync(string accessToken) {
            this.logoutAsync(accessToken, null);
        }
        
        /// <remarks/>
        public void logoutAsync(string accessToken, object userState) {
            if ((this.logoutOperationCompleted == null)) {
                this.logoutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlogoutOperationCompleted);
            }
            this.InvokeAsync("logout", new object[] {
                        accessToken}, this.logoutOperationCompleted, userState);
        }
        
        private void OnlogoutOperationCompleted(object arg) {
            if ((this.logoutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.logoutCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:authGiaMigByIDPassword", RequestNamespace="http://webmethod.svccom.tsukuba.kubota.co.jp", ResponseNamespace="http://webmethod.svccom.tsukuba.kubota.co.jp", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public WSUserInfoDto authGiaMigByIDPassword([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string apName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, bool uncryptedOption, [System.Xml.Serialization.XmlIgnoreAttribute()] bool uncryptedOptionSpecified, bool useGuestUserOption, [System.Xml.Serialization.XmlIgnoreAttribute()] bool useGuestUserOptionSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string clientIPAddress) {
            object[] results = this.Invoke("authGiaMigByIDPassword", new object[] {
                        apName,
                        userId,
                        password,
                        uncryptedOption,
                        uncryptedOptionSpecified,
                        useGuestUserOption,
                        useGuestUserOptionSpecified,
                        clientIPAddress});
            return ((WSUserInfoDto)(results[0]));
        }
        
        /// <remarks/>
        public void authGiaMigByIDPasswordAsync(string apName, string userId, string password, bool uncryptedOption, bool uncryptedOptionSpecified, bool useGuestUserOption, bool useGuestUserOptionSpecified, string clientIPAddress) {
            this.authGiaMigByIDPasswordAsync(apName, userId, password, uncryptedOption, uncryptedOptionSpecified, useGuestUserOption, useGuestUserOptionSpecified, clientIPAddress, null);
        }
        
        /// <remarks/>
        public void authGiaMigByIDPasswordAsync(string apName, string userId, string password, bool uncryptedOption, bool uncryptedOptionSpecified, bool useGuestUserOption, bool useGuestUserOptionSpecified, string clientIPAddress, object userState) {
            if ((this.authGiaMigByIDPasswordOperationCompleted == null)) {
                this.authGiaMigByIDPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnauthGiaMigByIDPasswordOperationCompleted);
            }
            this.InvokeAsync("authGiaMigByIDPassword", new object[] {
                        apName,
                        userId,
                        password,
                        uncryptedOption,
                        uncryptedOptionSpecified,
                        useGuestUserOption,
                        useGuestUserOptionSpecified,
                        clientIPAddress}, this.authGiaMigByIDPasswordOperationCompleted, userState);
        }
        
        private void OnauthGiaMigByIDPasswordOperationCompleted(object arg) {
            if ((this.authGiaMigByIDPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.authGiaMigByIDPasswordCompleted(this, new authGiaMigByIDPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:authMigByIDPassword", RequestNamespace="http://webmethod.svccom.tsukuba.kubota.co.jp", ResponseNamespace="http://webmethod.svccom.tsukuba.kubota.co.jp", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public WSUserInfoDto authMigByIDPassword([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string apName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, bool uncryptedOption, [System.Xml.Serialization.XmlIgnoreAttribute()] bool uncryptedOptionSpecified, bool useGuestUserOption, [System.Xml.Serialization.XmlIgnoreAttribute()] bool useGuestUserOptionSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string clientIPAddress) {
            object[] results = this.Invoke("authMigByIDPassword", new object[] {
                        apName,
                        userId,
                        password,
                        uncryptedOption,
                        uncryptedOptionSpecified,
                        useGuestUserOption,
                        useGuestUserOptionSpecified,
                        clientIPAddress});
            return ((WSUserInfoDto)(results[0]));
        }
        
        /// <remarks/>
        public void authMigByIDPasswordAsync(string apName, string userId, string password, bool uncryptedOption, bool uncryptedOptionSpecified, bool useGuestUserOption, bool useGuestUserOptionSpecified, string clientIPAddress) {
            this.authMigByIDPasswordAsync(apName, userId, password, uncryptedOption, uncryptedOptionSpecified, useGuestUserOption, useGuestUserOptionSpecified, clientIPAddress, null);
        }
        
        /// <remarks/>
        public void authMigByIDPasswordAsync(string apName, string userId, string password, bool uncryptedOption, bool uncryptedOptionSpecified, bool useGuestUserOption, bool useGuestUserOptionSpecified, string clientIPAddress, object userState) {
            if ((this.authMigByIDPasswordOperationCompleted == null)) {
                this.authMigByIDPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnauthMigByIDPasswordOperationCompleted);
            }
            this.InvokeAsync("authMigByIDPassword", new object[] {
                        apName,
                        userId,
                        password,
                        uncryptedOption,
                        uncryptedOptionSpecified,
                        useGuestUserOption,
                        useGuestUserOptionSpecified,
                        clientIPAddress}, this.authMigByIDPasswordOperationCompleted, userState);
        }
        
        private void OnauthMigByIDPasswordOperationCompleted(object arg) {
            if ((this.authMigByIDPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.authMigByIDPasswordCompleted(this, new authMigByIDPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:authByIDPassword", RequestNamespace="http://webmethod.svccom.tsukuba.kubota.co.jp", ResponseNamespace="http://webmethod.svccom.tsukuba.kubota.co.jp", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public WSUserInfoDto authByIDPassword([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string apName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, bool uncryptedOption, [System.Xml.Serialization.XmlIgnoreAttribute()] bool uncryptedOptionSpecified, bool useGuestUserOption, [System.Xml.Serialization.XmlIgnoreAttribute()] bool useGuestUserOptionSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string clientIPAddress) {
            object[] results = this.Invoke("authByIDPassword", new object[] {
                        apName,
                        userId,
                        password,
                        uncryptedOption,
                        uncryptedOptionSpecified,
                        useGuestUserOption,
                        useGuestUserOptionSpecified,
                        clientIPAddress});
            return ((WSUserInfoDto)(results[0]));
        }
        
        /// <remarks/>
        public void authByIDPasswordAsync(string apName, string userId, string password, bool uncryptedOption, bool uncryptedOptionSpecified, bool useGuestUserOption, bool useGuestUserOptionSpecified, string clientIPAddress) {
            this.authByIDPasswordAsync(apName, userId, password, uncryptedOption, uncryptedOptionSpecified, useGuestUserOption, useGuestUserOptionSpecified, clientIPAddress, null);
        }
        
        /// <remarks/>
        public void authByIDPasswordAsync(string apName, string userId, string password, bool uncryptedOption, bool uncryptedOptionSpecified, bool useGuestUserOption, bool useGuestUserOptionSpecified, string clientIPAddress, object userState) {
            if ((this.authByIDPasswordOperationCompleted == null)) {
                this.authByIDPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnauthByIDPasswordOperationCompleted);
            }
            this.InvokeAsync("authByIDPassword", new object[] {
                        apName,
                        userId,
                        password,
                        uncryptedOption,
                        uncryptedOptionSpecified,
                        useGuestUserOption,
                        useGuestUserOptionSpecified,
                        clientIPAddress}, this.authByIDPasswordOperationCompleted, userState);
        }
        
        private void OnauthByIDPasswordOperationCompleted(object arg) {
            if ((this.authByIDPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.authByIDPasswordCompleted(this, new authByIDPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:changePassword", RequestNamespace="http://webmethod.svccom.tsukuba.kubota.co.jp", ResponseNamespace="http://webmethod.svccom.tsukuba.kubota.co.jp", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public WSChangePwdDto changePassword([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string accessToken, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string oldPassword, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string newPassword, bool uncryptedOption, [System.Xml.Serialization.XmlIgnoreAttribute()] bool uncryptedOptionSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string clientIPAddress) {
            object[] results = this.Invoke("changePassword", new object[] {
                        accessToken,
                        userId,
                        oldPassword,
                        newPassword,
                        uncryptedOption,
                        uncryptedOptionSpecified,
                        clientIPAddress});
            return ((WSChangePwdDto)(results[0]));
        }
        
        /// <remarks/>
        public void changePasswordAsync(string accessToken, string userId, string oldPassword, string newPassword, bool uncryptedOption, bool uncryptedOptionSpecified, string clientIPAddress) {
            this.changePasswordAsync(accessToken, userId, oldPassword, newPassword, uncryptedOption, uncryptedOptionSpecified, clientIPAddress, null);
        }
        
        /// <remarks/>
        public void changePasswordAsync(string accessToken, string userId, string oldPassword, string newPassword, bool uncryptedOption, bool uncryptedOptionSpecified, string clientIPAddress, object userState) {
            if ((this.changePasswordOperationCompleted == null)) {
                this.changePasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnchangePasswordOperationCompleted);
            }
            this.InvokeAsync("changePassword", new object[] {
                        accessToken,
                        userId,
                        oldPassword,
                        newPassword,
                        uncryptedOption,
                        uncryptedOptionSpecified,
                        clientIPAddress}, this.changePasswordOperationCompleted, userState);
        }
        
        private void OnchangePasswordOperationCompleted(object arg) {
            if ((this.changePasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.changePasswordCompleted(this, new changePasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:authGiaMigByIPAddress", RequestNamespace="http://webmethod.svccom.tsukuba.kubota.co.jp", ResponseNamespace="http://webmethod.svccom.tsukuba.kubota.co.jp", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public WSUserInfoDto authGiaMigByIPAddress([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string apName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string clientIPAddress) {
            object[] results = this.Invoke("authGiaMigByIPAddress", new object[] {
                        apName,
                        clientIPAddress});
            return ((WSUserInfoDto)(results[0]));
        }
        
        /// <remarks/>
        public void authGiaMigByIPAddressAsync(string apName, string clientIPAddress) {
            this.authGiaMigByIPAddressAsync(apName, clientIPAddress, null);
        }
        
        /// <remarks/>
        public void authGiaMigByIPAddressAsync(string apName, string clientIPAddress, object userState) {
            if ((this.authGiaMigByIPAddressOperationCompleted == null)) {
                this.authGiaMigByIPAddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnauthGiaMigByIPAddressOperationCompleted);
            }
            this.InvokeAsync("authGiaMigByIPAddress", new object[] {
                        apName,
                        clientIPAddress}, this.authGiaMigByIPAddressOperationCompleted, userState);
        }
        
        private void OnauthGiaMigByIPAddressOperationCompleted(object arg) {
            if ((this.authGiaMigByIPAddressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.authGiaMigByIPAddressCompleted(this, new authGiaMigByIPAddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.svccom.tsukuba.kubota.co.jp/xsd")]
    public partial class WSUserInfoDto {
        
        private string accessTokenField;
        
        private string apAuthField;
        
        private string apDisplayNameField;
        
        private string apIdField;
        
        private string apInfoField;
        
        private string apNameField;
        
        private ApPrivilegeMasterDto[] apPrivilegeMasterListField;
        
        private string apRemarksField;
        
        private long authDateField;
        
        private bool authDateFieldSpecified;
        
        private string authMethodField;
        
        private string authResultCodeField;
        
        private string authResultMessageField;
        
        private long birthDayField;
        
        private bool birthDayFieldSpecified;
        
        private string buCodeField;
        
        private string bumonCodeField;
        
        private string bumonNameField;
        
        private string companyCodeField;
        
        private string companyNameField;
        
        private string companyName2Field;
        
        private string companyNameKanaField;
        
        private string companyNameKana2Field;
        
        private System.Nullable<int> expiredDaysField;
        
        private bool expiredDaysFieldSpecified;
        
        private System.Nullable<int> expiredSignField;
        
        private bool expiredSignFieldSpecified;
        
        private long idYukoEndDateField;
        
        private bool idYukoEndDateFieldSpecified;
        
        private long idYukoStartDateField;
        
        private bool idYukoStartDateFieldSpecified;
        
        private string ipAddressField;
        
        private System.Nullable<int> ipAddress1Field;
        
        private bool ipAddress1FieldSpecified;
        
        private System.Nullable<int> ipAddress2Field;
        
        private bool ipAddress2FieldSpecified;
        
        private System.Nullable<int> ipAddress3Field;
        
        private bool ipAddress3FieldSpecified;
        
        private System.Nullable<int> ipAddress4Field;
        
        private bool ipAddress4FieldSpecified;
        
        private string jiginouKubunField;
        
        private string kikiKubunNameField;
        
        private string kumiaiKubunField;
        
        private string lineCodeField;
        
        private string lineNameField;
        
        private string lineRyakugoField;
        
        private long loginDateField;
        
        private bool loginDateFieldSpecified;
        
        private string mailAddressField;
        
        private long nyuusyaDateField;
        
        private bool nyuusyaDateFieldSpecified;
        
        private string resultCodeField;
        
        private string resultMessageField;
        
        private string sagyochoNameField;
        
        private string seibetsuField;
        
        private string syainIDField;
        
        private string syainKubunField;
        
        private string syainNameKanaField;
        
        private string syainNameKanjiField;
        
        private string syokuchoNameField;
        
        private string syozokuKubunField;
        
        private long taisyaDateField;
        
        private bool taisyaDateFieldSpecified;
        
        private string[] taskListField;
        
        private long tekiyoFromDateField;
        
        private bool tekiyoFromDateFieldSpecified;
        
        private long tekiyoToDateField;
        
        private bool tekiyoToDateFieldSpecified;
        
        private string termKaCodeField;
        
        private string termKaNameField;
        
        private string termLineCodeField;
        
        private string termLineNameField;
        
        private string termLineShortNameField;
        
        private string terminalCodeField;
        
        private string terminalNameField;
        
        private string tyokukanKubunField;
        
        private string userIdField;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string accessToken {
            get {
                return this.accessTokenField;
            }
            set {
                this.accessTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string apAuth {
            get {
                return this.apAuthField;
            }
            set {
                this.apAuthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string apDisplayName {
            get {
                return this.apDisplayNameField;
            }
            set {
                this.apDisplayNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string apId {
            get {
                return this.apIdField;
            }
            set {
                this.apIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string apInfo {
            get {
                return this.apInfoField;
            }
            set {
                this.apInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string apName {
            get {
                return this.apNameField;
            }
            set {
                this.apNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("apPrivilegeMasterList", IsNullable=true)]
        public ApPrivilegeMasterDto[] apPrivilegeMasterList {
            get {
                return this.apPrivilegeMasterListField;
            }
            set {
                this.apPrivilegeMasterListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string apRemarks {
            get {
                return this.apRemarksField;
            }
            set {
                this.apRemarksField = value;
            }
        }
        
        /// <remarks/>
        public long authDate {
            get {
                return this.authDateField;
            }
            set {
                this.authDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool authDateSpecified {
            get {
                return this.authDateFieldSpecified;
            }
            set {
                this.authDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string authMethod {
            get {
                return this.authMethodField;
            }
            set {
                this.authMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string authResultCode {
            get {
                return this.authResultCodeField;
            }
            set {
                this.authResultCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string authResultMessage {
            get {
                return this.authResultMessageField;
            }
            set {
                this.authResultMessageField = value;
            }
        }
        
        /// <remarks/>
        public long birthDay {
            get {
                return this.birthDayField;
            }
            set {
                this.birthDayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool birthDaySpecified {
            get {
                return this.birthDayFieldSpecified;
            }
            set {
                this.birthDayFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string buCode {
            get {
                return this.buCodeField;
            }
            set {
                this.buCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string bumonCode {
            get {
                return this.bumonCodeField;
            }
            set {
                this.bumonCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string bumonName {
            get {
                return this.bumonNameField;
            }
            set {
                this.bumonNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string companyCode {
            get {
                return this.companyCodeField;
            }
            set {
                this.companyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string companyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string companyName2 {
            get {
                return this.companyName2Field;
            }
            set {
                this.companyName2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string companyNameKana {
            get {
                return this.companyNameKanaField;
            }
            set {
                this.companyNameKanaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string companyNameKana2 {
            get {
                return this.companyNameKana2Field;
            }
            set {
                this.companyNameKana2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> expiredDays {
            get {
                return this.expiredDaysField;
            }
            set {
                this.expiredDaysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expiredDaysSpecified {
            get {
                return this.expiredDaysFieldSpecified;
            }
            set {
                this.expiredDaysFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> expiredSign {
            get {
                return this.expiredSignField;
            }
            set {
                this.expiredSignField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expiredSignSpecified {
            get {
                return this.expiredSignFieldSpecified;
            }
            set {
                this.expiredSignFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long idYukoEndDate {
            get {
                return this.idYukoEndDateField;
            }
            set {
                this.idYukoEndDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idYukoEndDateSpecified {
            get {
                return this.idYukoEndDateFieldSpecified;
            }
            set {
                this.idYukoEndDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long idYukoStartDate {
            get {
                return this.idYukoStartDateField;
            }
            set {
                this.idYukoStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idYukoStartDateSpecified {
            get {
                return this.idYukoStartDateFieldSpecified;
            }
            set {
                this.idYukoStartDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ipAddress {
            get {
                return this.ipAddressField;
            }
            set {
                this.ipAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ipAddress1 {
            get {
                return this.ipAddress1Field;
            }
            set {
                this.ipAddress1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ipAddress1Specified {
            get {
                return this.ipAddress1FieldSpecified;
            }
            set {
                this.ipAddress1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ipAddress2 {
            get {
                return this.ipAddress2Field;
            }
            set {
                this.ipAddress2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ipAddress2Specified {
            get {
                return this.ipAddress2FieldSpecified;
            }
            set {
                this.ipAddress2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ipAddress3 {
            get {
                return this.ipAddress3Field;
            }
            set {
                this.ipAddress3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ipAddress3Specified {
            get {
                return this.ipAddress3FieldSpecified;
            }
            set {
                this.ipAddress3FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ipAddress4 {
            get {
                return this.ipAddress4Field;
            }
            set {
                this.ipAddress4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ipAddress4Specified {
            get {
                return this.ipAddress4FieldSpecified;
            }
            set {
                this.ipAddress4FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string jiginouKubun {
            get {
                return this.jiginouKubunField;
            }
            set {
                this.jiginouKubunField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string kikiKubunName {
            get {
                return this.kikiKubunNameField;
            }
            set {
                this.kikiKubunNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string kumiaiKubun {
            get {
                return this.kumiaiKubunField;
            }
            set {
                this.kumiaiKubunField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string lineCode {
            get {
                return this.lineCodeField;
            }
            set {
                this.lineCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string lineName {
            get {
                return this.lineNameField;
            }
            set {
                this.lineNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string lineRyakugo {
            get {
                return this.lineRyakugoField;
            }
            set {
                this.lineRyakugoField = value;
            }
        }
        
        /// <remarks/>
        public long loginDate {
            get {
                return this.loginDateField;
            }
            set {
                this.loginDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool loginDateSpecified {
            get {
                return this.loginDateFieldSpecified;
            }
            set {
                this.loginDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mailAddress {
            get {
                return this.mailAddressField;
            }
            set {
                this.mailAddressField = value;
            }
        }
        
        /// <remarks/>
        public long nyuusyaDate {
            get {
                return this.nyuusyaDateField;
            }
            set {
                this.nyuusyaDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nyuusyaDateSpecified {
            get {
                return this.nyuusyaDateFieldSpecified;
            }
            set {
                this.nyuusyaDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string resultMessage {
            get {
                return this.resultMessageField;
            }
            set {
                this.resultMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sagyochoName {
            get {
                return this.sagyochoNameField;
            }
            set {
                this.sagyochoNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string seibetsu {
            get {
                return this.seibetsuField;
            }
            set {
                this.seibetsuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string syainID {
            get {
                return this.syainIDField;
            }
            set {
                this.syainIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string syainKubun {
            get {
                return this.syainKubunField;
            }
            set {
                this.syainKubunField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string syainNameKana {
            get {
                return this.syainNameKanaField;
            }
            set {
                this.syainNameKanaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string syainNameKanji {
            get {
                return this.syainNameKanjiField;
            }
            set {
                this.syainNameKanjiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string syokuchoName {
            get {
                return this.syokuchoNameField;
            }
            set {
                this.syokuchoNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string syozokuKubun {
            get {
                return this.syozokuKubunField;
            }
            set {
                this.syozokuKubunField = value;
            }
        }
        
        /// <remarks/>
        public long taisyaDate {
            get {
                return this.taisyaDateField;
            }
            set {
                this.taisyaDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool taisyaDateSpecified {
            get {
                return this.taisyaDateFieldSpecified;
            }
            set {
                this.taisyaDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("taskList", IsNullable=true)]
        public string[] taskList {
            get {
                return this.taskListField;
            }
            set {
                this.taskListField = value;
            }
        }
        
        /// <remarks/>
        public long tekiyoFromDate {
            get {
                return this.tekiyoFromDateField;
            }
            set {
                this.tekiyoFromDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tekiyoFromDateSpecified {
            get {
                return this.tekiyoFromDateFieldSpecified;
            }
            set {
                this.tekiyoFromDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long tekiyoToDate {
            get {
                return this.tekiyoToDateField;
            }
            set {
                this.tekiyoToDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tekiyoToDateSpecified {
            get {
                return this.tekiyoToDateFieldSpecified;
            }
            set {
                this.tekiyoToDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string termKaCode {
            get {
                return this.termKaCodeField;
            }
            set {
                this.termKaCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string termKaName {
            get {
                return this.termKaNameField;
            }
            set {
                this.termKaNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string termLineCode {
            get {
                return this.termLineCodeField;
            }
            set {
                this.termLineCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string termLineName {
            get {
                return this.termLineNameField;
            }
            set {
                this.termLineNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string termLineShortName {
            get {
                return this.termLineShortNameField;
            }
            set {
                this.termLineShortNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string terminalCode {
            get {
                return this.terminalCodeField;
            }
            set {
                this.terminalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string terminalName {
            get {
                return this.terminalNameField;
            }
            set {
                this.terminalNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tyokukanKubun {
            get {
                return this.tyokukanKubunField;
            }
            set {
                this.tyokukanKubunField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gia.dto.ibatis.ktutil4.tsukuba.kubota.co.jp/xsd")]
    public partial class ApPrivilegeMasterDto {
        
        private string apAuthField;
        
        private string apIdField;
        
        private int indexField;
        
        private bool indexFieldSpecified;
        
        private string taskIdField;
        
        private string userIdField;
        
        private string userInfo1Field;
        
        private string userInfo10Field;
        
        private string userInfo2Field;
        
        private string userInfo3Field;
        
        private string userInfo4Field;
        
        private string userInfo5Field;
        
        private string userInfo6Field;
        
        private string userInfo7Field;
        
        private string userInfo8Field;
        
        private string userInfo9Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string apAuth {
            get {
                return this.apAuthField;
            }
            set {
                this.apAuthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string apId {
            get {
                return this.apIdField;
            }
            set {
                this.apIdField = value;
            }
        }
        
        /// <remarks/>
        public int index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool indexSpecified {
            get {
                return this.indexFieldSpecified;
            }
            set {
                this.indexFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string taskId {
            get {
                return this.taskIdField;
            }
            set {
                this.taskIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userInfo1 {
            get {
                return this.userInfo1Field;
            }
            set {
                this.userInfo1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userInfo10 {
            get {
                return this.userInfo10Field;
            }
            set {
                this.userInfo10Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userInfo2 {
            get {
                return this.userInfo2Field;
            }
            set {
                this.userInfo2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userInfo3 {
            get {
                return this.userInfo3Field;
            }
            set {
                this.userInfo3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userInfo4 {
            get {
                return this.userInfo4Field;
            }
            set {
                this.userInfo4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userInfo5 {
            get {
                return this.userInfo5Field;
            }
            set {
                this.userInfo5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userInfo6 {
            get {
                return this.userInfo6Field;
            }
            set {
                this.userInfo6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userInfo7 {
            get {
                return this.userInfo7Field;
            }
            set {
                this.userInfo7Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userInfo8 {
            get {
                return this.userInfo8Field;
            }
            set {
                this.userInfo8Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userInfo9 {
            get {
                return this.userInfo9Field;
            }
            set {
                this.userInfo9Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.svccom.tsukuba.kubota.co.jp/xsd")]
    public partial class WSChangePwdDto {
        
        private string resultCodeField;
        
        private string resultMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string resultMessage {
            get {
                return this.resultMessageField;
            }
            set {
                this.resultMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void authByActiveDirectoryCompletedEventHandler(object sender, authByActiveDirectoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class authByActiveDirectoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal authByActiveDirectoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WSUserInfoDto Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WSUserInfoDto)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void logoutCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void authGiaMigByIDPasswordCompletedEventHandler(object sender, authGiaMigByIDPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class authGiaMigByIDPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal authGiaMigByIDPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WSUserInfoDto Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WSUserInfoDto)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void authMigByIDPasswordCompletedEventHandler(object sender, authMigByIDPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class authMigByIDPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal authMigByIDPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WSUserInfoDto Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WSUserInfoDto)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void authByIDPasswordCompletedEventHandler(object sender, authByIDPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class authByIDPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal authByIDPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WSUserInfoDto Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WSUserInfoDto)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void changePasswordCompletedEventHandler(object sender, changePasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class changePasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal changePasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WSChangePwdDto Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WSChangePwdDto)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void authGiaMigByIPAddressCompletedEventHandler(object sender, authGiaMigByIPAddressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class authGiaMigByIPAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal authGiaMigByIPAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WSUserInfoDto Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WSUserInfoDto)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591