//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRC_W_PWT_ProductView.UI.Pages.UserControl {
    
    
    public partial class MainProcessPartialView {
        
        /// <summary>
        /// divEngineInjection03Condition control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divEngineInjection03Condition;
        
        /// <summary>
        /// engineInjection03_cldStart control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTCalendar engineInjection03_cldStart;
        
        /// <summary>
        /// engineInjection03_cldEnd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTCalendar engineInjection03_cldEnd;
        
        /// <summary>
        /// engineInjection03_txtIntegratedCd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox engineInjection03_txtIntegratedCd;
        
        /// <summary>
        /// engineInjection03_ddlMeasurementTerminalKind control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTDropDownList engineInjection03_ddlMeasurementTerminalKind;
        
        /// <summary>
        /// engineInjection03_ddlResultKind control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTDropDownList engineInjection03_ddlResultKind;
        
        /// <summary>
        /// divEngineInjection07Condition control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divEngineInjection07Condition;
        
        /// <summary>
        /// engineInjection07_cldStart control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTCalendar engineInjection07_cldStart;
        
        /// <summary>
        /// engineInjection07_cldEnd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTCalendar engineInjection07_cldEnd;
        
        /// <summary>
        /// engineInjection07_ddlResultKind control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTDropDownList engineInjection07_ddlResultKind;
        
        /// <summary>
        /// divEngineFrictionCondition control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divEngineFrictionCondition;
        
        /// <summary>
        /// engineFriction_cldStart control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTCalendar engineFriction_cldStart;
        
        /// <summary>
        /// engineFriction_cldEnd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTCalendar engineFriction_cldEnd;
        
        /// <summary>
        /// engineFriction_ddlResultKind control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTDropDownList engineFriction_ddlResultKind;
        
        /// <summary>
        /// divEngineTest03Condition control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divEngineTest03Condition;
        
        /// <summary>
        /// engineTest03_cldStart control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTCalendar engineTest03_cldStart;
        
        /// <summary>
        /// engineTest03_cldEnd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTCalendar engineTest03_cldEnd;
        
        /// <summary>
        /// engineTest03_ddlResultKind control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTDropDownList engineTest03_ddlResultKind;
        
        /// <summary>
        /// divEngineTest07Condition control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divEngineTest07Condition;
        
        /// <summary>
        /// engineTest07_cldStart control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTCalendar engineTest07_cldStart;
        
        /// <summary>
        /// engineTest07_cldEnd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTCalendar engineTest07_cldEnd;
        
        /// <summary>
        /// engineTest07_ddlResultKind control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTDropDownList engineTest07_ddlResultKind;
    }
}
