//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRC_W_PWT_ProductView.UI.Pages.ProcessView {
    
    
    public partial class TractorAll {
        
        /// <summary>
        /// SubScripts control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder SubScripts;
        
        /// <summary>
        /// btnExcel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTButton btnExcel;
        
        /// <summary>
        /// divMainHeaderLT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divMainHeaderLT;
        
        /// <summary>
        /// solidLTMainHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable solidLTMainHeader;
        
        /// <summary>
        /// headerLTMainContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow headerLTMainContent;
        
        /// <summary>
        /// InspectionSeq control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell InspectionSeq;
        
        /// <summary>
        /// divMainHeaderRT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divMainHeaderRT;
        
        /// <summary>
        /// solidMainRTHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable solidMainRTHeader;
        
        /// <summary>
        /// headerRTMainContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow headerRTMainContent;
        
        /// <summary>
        /// Result control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell Result;
        
        /// <summary>
        /// InspectionEmplCd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell InspectionEmplCd;
        
        /// <summary>
        /// InspectionDt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell InspectionDt;
        
        /// <summary>
        /// divGrvLBMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divGrvLBMain;
        
        /// <summary>
        /// lstMainListLB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ListView lstMainListLB;
        
        /// <summary>
        /// divGrvRBMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divGrvRBMain;
        
        /// <summary>
        /// lstMainListRB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ListView lstMainListRB;
        
        /// <summary>
        /// txtInspectionDt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtInspectionDt;
        
        /// <summary>
        /// txtInspectionSeq control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtInspectionSeq;
        
        /// <summary>
        /// txtSeqenceNum control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtSeqenceNum;
        
        /// <summary>
        /// txtPinCd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtPinCd;
        
        /// <summary>
        /// txtInspectionGroup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtInspectionGroup;
        
        /// <summary>
        /// txtWheelDrive control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtWheelDrive;
        
        /// <summary>
        /// txtLashingHookF control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtLashingHookF;
        
        /// <summary>
        /// txtLashingHookR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtLashingHookR;
        
        /// <summary>
        /// txtJigComF control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtJigComF;
        
        /// <summary>
        /// txtJigComR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtJigComR;
        
        /// <summary>
        /// txtMaxSpeedFlagDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtMaxSpeedFlagDetail;
        
        /// <summary>
        /// txtMaxSpeedStationCdDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtMaxSpeedStationCdDetail;
        
        /// <summary>
        /// div2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl div2;
        
        /// <summary>
        /// Tr1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow Tr1;
        
        /// <summary>
        /// Th1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell Th1;
        
        /// <summary>
        /// Th2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell Th2;
        
        /// <summary>
        /// Th3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell Th3;
        
        /// <summary>
        /// Th4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell Th4;
        
        /// <summary>
        /// Th5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell Th5;
        
        /// <summary>
        /// Th6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell Th6;
        
        /// <summary>
        /// Th7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell Th7;
        
        /// <summary>
        /// Th8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell Th8;
        
        /// <summary>
        /// Th9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell Th9;
        
        /// <summary>
        /// Th19 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell Th19;
        
        /// <summary>
        /// Th10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell Th10;
        
        /// <summary>
        /// Th11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell Th11;
        
        /// <summary>
        /// Th12 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell Th12;
        
        /// <summary>
        /// Th13 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell Th13;
        
        /// <summary>
        /// Th14 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell Th14;
        
        /// <summary>
        /// Th15 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell Th15;
        
        /// <summary>
        /// Th16 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell Th16;
        
        /// <summary>
        /// Th17 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell Th17;
        
        /// <summary>
        /// Th18 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell Th18;
        
        /// <summary>
        /// div6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl div6;
        
        /// <summary>
        /// lstSpeedIns control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ListView lstSpeedIns;
        
        /// <summary>
        /// txtNoiseFlag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtNoiseFlag;
        
        /// <summary>
        /// txtSubTransmission control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtSubTransmission;
        
        /// <summary>
        /// txtMainTransmission control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtMainTransmission;
        
        /// <summary>
        /// txtNoiseFrontWheelMin control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtNoiseFrontWheelMin;
        
        /// <summary>
        /// txtNoiseFrontWheelMax control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtNoiseFrontWheelMax;
        
        /// <summary>
        /// txtNoiseRearWheelMin control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtNoiseRearWheelMin;
        
        /// <summary>
        /// txtNoiseRearWheelMax control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtNoiseRearWheelMax;
        
        /// <summary>
        /// txtNoiseRangeHoldTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtNoiseRangeHoldTime;
        
        /// <summary>
        /// txtNoiseCloseTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtNoiseCloseTime;
        
        /// <summary>
        /// txtRtNoiseFlag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtNoiseFlag;
        
        /// <summary>
        /// txtRtNoiseEndTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtNoiseEndTime;
        
        /// <summary>
        /// txtRtNoiseFrontWheelL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtNoiseFrontWheelL;
        
        /// <summary>
        /// txtRtNoiseFrontWheelR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtNoiseFrontWheelR;
        
        /// <summary>
        /// txtRtNoiseRearWheelL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtNoiseRearWheelL;
        
        /// <summary>
        /// txtRtNoiseRearWheelR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtNoiseRearWheelR;
        
        /// <summary>
        /// txtRtNoiseFrontWheelLCv control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtNoiseFrontWheelLCv;
        
        /// <summary>
        /// txtRtNoiseFrontWheelRCv control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtNoiseFrontWheelRCv;
        
        /// <summary>
        /// txtRtNoiseRearWheelLCv control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtNoiseRearWheelLCv;
        
        /// <summary>
        /// txtRtNoiseRearWheelRCv control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtNoiseRearWheelRCv;
        
        /// <summary>
        /// txtRtNoiseMax control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtNoiseMax;
        
        /// <summary>
        /// txtNoiseThresholdMin control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtNoiseThresholdMin;
        
        /// <summary>
        /// txtNoiseStationCd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtNoiseStationCd;
        
        /// <summary>
        /// txtNoiseThreshold control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtNoiseThreshold;
        
        /// <summary>
        /// txtAbnormalNoiseFlag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtAbnormalNoiseFlag;
        
        /// <summary>
        /// txtRtAbnormalNoiseEndTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtAbnormalNoiseEndTime;
        
        /// <summary>
        /// txtRtAbnormalNoiseFlag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtAbnormalNoiseFlag;
        
        /// <summary>
        /// txtSisStationCd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtSisStationCd;
        
        /// <summary>
        /// txtMaxAllowWeight control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtMaxAllowWeight;
        
        /// <summary>
        /// txtBrakingForceLRDiff control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtBrakingForceLRDiff;
        
        /// <summary>
        /// txtBrakingComCloseTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtBrakingComCloseTime;
        
        /// <summary>
        /// txtBrakingBFlag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtBrakingBFlag;
        
        /// <summary>
        /// txtBrakingBForceMin control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtBrakingBForceMin;
        
        /// <summary>
        /// txtBrakingBThreshold control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtBrakingBThreshold;
        
        /// <summary>
        /// txtBrakingBForceMax control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtBrakingBForceMax;
        
        /// <summary>
        /// txtBrakingBThresholdMax control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtBrakingBThresholdMax;
        
        /// <summary>
        /// txtBrkbStationCd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtBrkbStationCd;
        
        /// <summary>
        /// txtBrakingPFlag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtBrakingPFlag;
        
        /// <summary>
        /// txtBrakingPThreshold control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtBrakingPThreshold;
        
        /// <summary>
        /// txtBrkpStationCd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtBrkpStationCd;
        
        /// <summary>
        /// txtBrakingPThresholdMax control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtBrakingPThresholdMax;
        
        /// <summary>
        /// txtBrakingEFlag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtBrakingEFlag;
        
        /// <summary>
        /// txtBrakingEThreshold control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtBrakingEThreshold;
        
        /// <summary>
        /// txtBrkeStationCd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtBrkeStationCd;
        
        /// <summary>
        /// txtBrakingEThresholdMax control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtBrakingEThresholdMax;
        
        /// <summary>
        /// txtRtBrkBFlag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtBrkBFlag;
        
        /// <summary>
        /// txtRtBrkBEndTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtBrkBEndTime;
        
        /// <summary>
        /// txtRtBrkBMaxForceRearL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtBrkBMaxForceRearL;
        
        /// <summary>
        /// txtRtBrkBMaxForceRearR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtBrkBMaxForceRearR;
        
        /// <summary>
        /// txtRtBrkBMaxForceRearLCv control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtBrkBMaxForceRearLCv;
        
        /// <summary>
        /// txtRtBrkBMaxForceRearRCv control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtBrkBMaxForceRearRCv;
        
        /// <summary>
        /// txtRtBrkBMaxPedalForceMax control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtBrkBMaxPedalForceMax;
        
        /// <summary>
        /// txtRtBrkPFlag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtBrkPFlag;
        
        /// <summary>
        /// txtRtBrkPEndTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtBrkPEndTime;
        
        /// <summary>
        /// txtRtBrkPMaxForceRearL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtBrkPMaxForceRearL;
        
        /// <summary>
        /// txtRtBrkPMaxForceRearR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtBrkPMaxForceRearR;
        
        /// <summary>
        /// txtRtBrkPMaxForceRearLCv control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtBrkPMaxForceRearLCv;
        
        /// <summary>
        /// txtRtBrkPMaxForceRearRCv control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtBrkPMaxForceRearRCv;
        
        /// <summary>
        /// txtRtBrkEFlag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtBrkEFlag;
        
        /// <summary>
        /// txtRtBrkEEndTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtBrkEEndTime;
        
        /// <summary>
        /// txtRtBrkEMaxForceRearL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtBrkEMaxForceRearL;
        
        /// <summary>
        /// txtRtBrkEMaxForceRearR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtBrkEMaxForceRearR;
        
        /// <summary>
        /// txtRtBrkEMaxForceRearLCv control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtBrkEMaxForceRearLCv;
        
        /// <summary>
        /// txtRtBrkEMaxForceRearRCv control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtBrkEMaxForceRearRCv;
        
        /// <summary>
        /// txtMonroeFlag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtMonroeFlag;
        
        /// <summary>
        /// txtRtMonroeEndTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtMonroeEndTime;
        
        /// <summary>
        /// txtRtMonroeFlag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtMonroeFlag;
        
        /// <summary>
        /// txtMonroeStationCd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtMonroeStationCd;
        
        /// <summary>
        /// txtPtoFlag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtPtoFlag;
        
        /// <summary>
        /// txtRtPtoEndTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtPtoEndTime;
        
        /// <summary>
        /// txtRtPtoFlag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtPtoFlag;
        
        /// <summary>
        /// txtPtoStationCd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtPtoStationCd;
        
        /// <summary>
        /// txtHydraulicFlag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtHydraulicFlag;
        
        /// <summary>
        /// txtHydraulicWeight control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtHydraulicWeight;
        
        /// <summary>
        /// txtHydraulicSling control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtHydraulicSling;
        
        /// <summary>
        /// txtHydraulicLowerLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtHydraulicLowerLink;
        
        /// <summary>
        /// txtRtHydraulicFlag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtHydraulicFlag;
        
        /// <summary>
        /// txtRtHydraulicEndTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtHydraulicEndTime;
        
        /// <summary>
        /// txtHydraulicStationCd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtHydraulicStationCd;
        
        /// <summary>
        /// txtHeadlightFlag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtHeadlightFlag;
        
        /// <summary>
        /// txtRtHeadlightEndTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtHeadlightEndTime;
        
        /// <summary>
        /// txtRtHeadlightFlag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtHeadlightFlag;
        
        /// <summary>
        /// txtHeadlightStationCd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtHeadlightStationCd;
        
        /// <summary>
        /// txtKeyStopFlag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtKeyStopFlag;
        
        /// <summary>
        /// txtRtKeyStopEmplEndTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtKeyStopEmplEndTime;
        
        /// <summary>
        /// txtRtKeyStopFlag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtKeyStopFlag;
        
        /// <summary>
        /// txtKeystopStationCd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtKeystopStationCd;
        
        /// <summary>
        /// txtSteeringTightenFlag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtSteeringTightenFlag;
        
        /// <summary>
        /// txtRtSteeringTightenEndTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtSteeringTightenEndTime;
        
        /// <summary>
        /// txtRtSteeringTightenFlag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtRtSteeringTightenFlag;
        
        /// <summary>
        /// txtStgtightenStationCd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtStgtightenStationCd;
    }
}
