//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRC_W_PWT_ProductView.UI.Pages.PartsView {
    
    
    public partial class Nameplate {
        
        /// <summary>
        /// SubScripts control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder SubScripts;
        
        /// <summary>
        /// divTractor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divTractor;
        
        /// <summary>
        /// txtPlateTypeTractor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtPlateTypeTractor;
        
        /// <summary>
        /// txtNamePlateCdTractor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtNamePlateCdTractor;
        
        /// <summary>
        /// txtNamePlateNmTractor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtNamePlateNmTractor;
        
        /// <summary>
        /// txtSubProductCdTractor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtSubProductCdTractor;
        
        /// <summary>
        /// txtPrintDtTractor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtPrintDtTractor;
        
        /// <summary>
        /// divCab control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divCab;
        
        /// <summary>
        /// txtPlateTypeCab control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtPlateTypeCab;
        
        /// <summary>
        /// txtNamePlateCdCab control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtNamePlateCdCab;
        
        /// <summary>
        /// txtNamePlateNmCab control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtNamePlateNmCab;
        
        /// <summary>
        /// txtSubProductCdCab control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtSubProductCdCab;
        
        /// <summary>
        /// txtPrintDtCab control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtPrintDtCab;
        
        /// <summary>
        /// divRops control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divRops;
        
        /// <summary>
        /// txtPlateTypeRops control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtPlateTypeRops;
        
        /// <summary>
        /// txtNamePlateCdRops control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtNamePlateCdRops;
        
        /// <summary>
        /// txtNamePlateNmRops control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtNamePlateNmRops;
        
        /// <summary>
        /// txtSubProductCdRops control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtSubProductCdRops;
        
        /// <summary>
        /// txtPrintDtRops control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KTWebControl.CustomControls.KTTextBox txtPrintDtRops;
    }
}
