//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRC_W_PWT_ProductView.UI.Pages.Kanban {


	public partial class KanbanPickingStatusView {

		/// <summary>
		/// upnCondition control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.UpdatePanel upnCondition;

		/// <summary>
		/// cldSendDateFrom control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTCalendar cldSendDateFrom;

		/// <summary>
		/// ttbSendTimeFrom control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTTimeTextBox ttbSendTimeFrom;

		/// <summary>
		/// cldSendDateTo control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTCalendar cldSendDateTo;

		/// <summary>
		/// ttbSendTimeTo control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTTimeTextBox ttbSendTimeTo;

		/// <summary>
		/// cldEndDateFrom control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTCalendar cldEndDateFrom;

		/// <summary>
		/// ttbEndTimeFrom control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTTimeTextBox ttbEndTimeFrom;

		/// <summary>
		/// cldEndDateTo control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTCalendar cldEndDateTo;

		/// <summary>
		/// ttbEndTimeTo control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTTimeTextBox ttbEndTimeTo;

		/// <summary>
		/// ddlStatus control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTDropDownList ddlStatus;

		/// <summary>
		/// ddlArea control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTDropDownList ddlArea;

		/// <summary>
		/// txtPickingUserNm control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTTextBox txtPickingUserNm;

		/// <summary>
		/// hdnPickingUserNm control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HiddenField hdnPickingUserNm;

		/// <summary>
		/// hdnPickingUserId control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HiddenField hdnPickingUserId;

		/// <summary>
		/// txtPickingNo control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTTextBox txtPickingNo;

		/// <summary>
		/// txtPartsNumber control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTTextBox txtPartsNumber;

		/// <summary>
		/// btnSearch control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTButton btnSearch;

		/// <summary>
		/// pnlPager control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Panel pnlPager;

		/// <summary>
		/// ntbResultCount control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTNumericTextBox ntbResultCount;

		/// <summary>
		/// divGrvDisplay control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.HtmlControls.HtmlGenericControl divGrvDisplay;

		/// <summary>
		/// divGrvHeaderLT control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.HtmlControls.HtmlGenericControl divGrvHeaderLT;

		/// <summary>
		/// grvPickingHeader control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.GridView grvPickingHeader;

		/// <summary>
		/// divGrvLB control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.HtmlControls.HtmlGenericControl divGrvLB;

		/// <summary>
		/// grvPickingBody control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.GridView grvPickingBody;

		/// <summary>
		/// divGrvCtrlButton control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.HtmlControls.HtmlGenericControl divGrvCtrlButton;

		/// <summary>
		/// btnExcel control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTButton btnExcel;
	}
}
