//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRC_W_PWT_ProductView.UI.Pages {


	public partial class MainView {

		/// <summary>
		/// ChangeProductSearch control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTButton ChangeProductSearch;

		/// <summary>
		/// ChangePartsSearch control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTButton ChangePartsSearch;

		/// <summary>
		/// ChangeProcessSearch control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTButton ChangeProcessSearch;

		/// <summary>
		/// upnCondition control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.UpdatePanel upnCondition;

		/// <summary>
		/// rblProductKind control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTRadioButtonList rblProductKind;

		/// <summary>
		/// rblModelType control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTRadioButtonList rblModelType;

		/// <summary>
		/// txtModelNm control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTTextBox txtModelNm;

		/// <summary>
		/// txtModelCd control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTTextBox txtModelCd;

		/// <summary>
		/// txtProductSerial control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTTextBox txtProductSerial;

		/// <summary>
		/// txtIDNO control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTTextBox txtIDNO;

		/// <summary>
		/// txtPinCd control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTTextBox txtPinCd;

		/// <summary>
		/// hdnLineCd control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HiddenField hdnLineCd;

		/// <summary>
		/// hdnProcessCd control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HiddenField hdnProcessCd;

		/// <summary>
		/// hdnWorkCd control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HiddenField hdnWorkCd;

		/// <summary>
		/// hdnSearchTargetFlg control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HiddenField hdnSearchTargetFlg;

		/// <summary>
		/// hdnProcessNm control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HiddenField hdnProcessNm;

		/// <summary>
		/// hdnWorkNm control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.HiddenField hdnWorkNm;

		/// <summary>
		/// btnChangeProcess control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTButton btnChangeProcess;

		/// <summary>
		/// txtProcessNm control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTTextBox txtProcessNm;

		/// <summary>
		/// txtWorkNm control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTTextBox txtWorkNm;

		/// <summary>
		/// ddlParts control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTDropDownList ddlParts;

		/// <summary>
		/// txtPartsNo control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTTextBox txtPartsNo;

		/// <summary>
		/// txtPartsSerial control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTTextBox txtPartsSerial;

		/// <summary>
		/// ddlDateKind control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTDropDownList ddlDateKind;

		/// <summary>
		/// cldStart control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTCalendar cldStart;

		/// <summary>
		/// cldEnd control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTCalendar cldEnd;

		/// <summary>
		/// chkPinCd control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.HtmlControls.HtmlInputCheckBox chkPinCd;

		/// <summary>
		/// btnMassDataOutput control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTButton btnMassDataOutput;

		/// <summary>
		/// btnSearch control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTButton btnSearch;

		/// <summary>
		/// pnlPager control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.Panel pnlPager;

		/// <summary>
		/// ntbResultCount control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTNumericTextBox ntbResultCount;

		/// <summary>
		/// divGrvDisplay control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.HtmlControls.HtmlGenericControl divGrvDisplay;

		/// <summary>
		/// divGrvHeaderLT control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.HtmlControls.HtmlGenericControl divGrvHeaderLT;

		/// <summary>
		/// grvHeaderLT control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.GridView grvHeaderLT;

		/// <summary>
		/// divGrvHeaderRT control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.HtmlControls.HtmlGenericControl divGrvHeaderRT;

		/// <summary>
		/// grvHeaderRT control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.GridView grvHeaderRT;

		/// <summary>
		/// divGrvLB control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.HtmlControls.HtmlGenericControl divGrvLB;

		/// <summary>
		/// grvMainViewLB control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.GridView grvMainViewLB;

		/// <summary>
		/// divGrvRB control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.HtmlControls.HtmlGenericControl divGrvRB;

		/// <summary>
		/// grvMainViewRB control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.WebControls.GridView grvMainViewRB;

		/// <summary>
		/// divGrvCtrlButton control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::System.Web.UI.HtmlControls.HtmlGenericControl divGrvCtrlButton;

		/// <summary>
		/// btnExcel control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::KTWebControl.CustomControls.KTButton btnExcel;
	}
}
